export const routePaths = {
  landing: "/",
  auth: {
    login: "/login",
    signup: "/signup",
  },
  platform: {
    root: "/platform",
    users: "/platform/users",
    subscriptions: "/platform/subscriptions",
    usage: "/platform/usage",
    flags: "/platform/flags",
    audit: "/platform/audit",
    support: "/platform/support",
  },
  app: {
    root: "/app",
    overview: "/app/overview",
    work: {
      root: "/app/work",
      domains: "/app/work/domains",
      initiatives: "/app/work/initiatives",
      valueStreams: (valueStreamId: string) => `/app/work/value-streams/${valueStreamId}`,
      domain: (domainId: string) => `/app/work/domains/${domainId}`,
      initiative: (initiativeId: string) => `/app/work/initiatives/${initiativeId}`,
    },
    horizon: {
      root: "/app/horizon",
      timeline: "/app/horizon/timeline",
      capacity: "/app/horizon/capacity",
      share: "/app/horizon/share",
    },
    people: {
      root: "/app/people",
      nineBox: "/app/people/9-box",
      employees: "/app/people/employees",
      employee: (employeeId: string) => `/app/people/employees/${employeeId}`,
      teams: "/app/people/teams",
      team: (teamId: string) => `/app/people/teams/${teamId}`,
    },
    skills: {
      root: "/app/skills",
      matrix: "/app/skills/matrix",
      coverage: "/app/skills/coverage",
      risk: "/app/skills/risk",
    },
    signals: {
      root: "/app/signals",
      teams: "/app/signals/teams",
      capacity: "/app/signals/capacity",
      resilience: "/app/signals/resilience",
    },
    insights: {
      root: "/app/insights",
      team: (teamId: string) => `/app/insights/team/${teamId}`,
    },
    admin: {
      root: "/app/admin",
      access: "/app/admin/access",
      users: "/app/admin/users",
      user: (userId: string) => `/app/admin/users/${userId}`,
      roles: "/app/admin/roles",
      linking: "/app/admin/linking",
      governance: "/app/admin/governance",
      audit: "/app/admin/audit",
    },
    account: {
      root: "/app/account",
      security: "/app/account/security",
      sessions: "/app/account/sessions",
      notifications: "/app/account/notifications",
      tokens: "/app/account/tokens",
    },
    help: "/app/help",
  },
} as const;
